### Sign up
POST http://localhost:3000/v1/auth/sign-up
Content-Type: application/json

{
    "username": "test3",
    "password": "test"
}

### Sign in
POST http://localhost:3000/v1/auth/sign-in
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}