name: Node.js CI

on:
  push:
    branches: [ main ]           # or your default branch
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18        # your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload coverage (optional)
        if: success() && github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
